export {default as ProductList} from "./product-list-child/Products-list-child"
export {default as SecondHeader} from "./second-header/header"
export {default as FirstHeader} from "./first-header/first"
export {default as DarkModeToggle} from "./dark-mode-toggler/dark"
export {default as Promo} from "./promo/promo"
export {default as Content} from "./content/content"
export {default as SideMenu} from "./side-menu/sidemenu"
export {default as TestComp} from "./test/test"